"""feat: update table schema

Revision ID: c4c7f194200b
Revises: 
Create Date: 2026-07-09 15:48:22.585819+08:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4c7f194200b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='手机号'),
    sa.Column('mail', sa.String(length=256), nullable=True, comment='邮箱'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='用户编号'),
    sa.Column('seat', sa.String(length=64), nullable=True, comment='座位编号'),
    sa.Column('department', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=64), nullable=True, comment='职位'),
    sa.Column('superior', sa.String(length=64), nullable=True, comment='上级'),
    sa.Column('login_type', sa.String(length=64), nullable=True, comment='登录类型:single;many'),
    sa.Column('is_tourist', sa.Integer(), nullable=False, comment='0-游客账户;1-非游客账户'),
    sa.Column('creator', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('creator_id', sa.BigInteger(), nullable=True, comment='创建人id'),
    sa.Column('modifier', sa.String(length=32), nullable=True, comment='更新人'),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True, comment='更新人id'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_data_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='数据源名称'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='数据源编码'),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='数据源类型'),
    sa.Column('host', sa.String(length=255), nullable=True, comment='主机地址'),
    sa.Column('port', sa.Integer(), nullable=True, comment='端口'),
    sa.Column('database', sa.String(length=128), nullable=True, comment='数据库名'),
    sa.Column('username', sa.String(length=128), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=512), nullable=True, comment='密码/密钥'),
    sa.Column('read_only', sa.Boolean(), nullable=False, comment='是否只读'),
    sa.Column('extra_config', sa.JSON(), nullable=False, comment='扩展配置'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('owner', sa.String(length=64), nullable=True, comment='负责人'),
    sa.Column('owner_id', sa.BigInteger(), nullable=True, comment='负责人ID'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_data_source_code'), 'ai_data_source', ['code'], unique=True)
    op.create_table('aps_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务id'),
    sa.Column('trigger_type', sa.String(length=16), nullable=False, comment='触发器类型:date;interval;cron'),
    sa.Column('trigger_param', sa.JSON(), nullable=False, comment='触发器参数'),
    sa.Column('task_function_name', sa.String(length=255), nullable=True, comment='任务函数名称'),
    sa.Column('task_function_args', sa.JSON(), nullable=False, comment='任务参数:args'),
    sa.Column('task_function_kwargs', sa.JSON(), nullable=False, comment='任务参数:kwargs'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_semantic_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('data_source_id', sa.Integer(), nullable=False, comment='数据源ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='语义模型名称'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='语义模型编码'),
    sa.Column('table_name', sa.String(length=128), nullable=False, comment='主表名'),
    sa.Column('table_description', sa.Text(), nullable=True, comment='表说明'),
    sa.Column('fields', sa.JSON(), nullable=False, comment='字段配置'),
    sa.Column('metrics', sa.JSON(), nullable=False, comment='指标配置'),
    sa.Column('dimensions', sa.JSON(), nullable=False, comment='维度配置'),
    sa.Column('terms', sa.JSON(), nullable=False, comment='业务术语'),
    sa.Column('example_questions', sa.JSON(), nullable=False, comment='示例问题'),
    sa.Column('prompt_hints', sa.Text(), nullable=True, comment='提示词补充说明'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('owner', sa.String(length=64), nullable=True, comment='负责人'),
    sa.Column('owner_id', sa.BigInteger(), nullable=True, comment='负责人ID'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.ForeignKeyConstraint(['data_source_id'], ['ai_data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_semantic_model_code'), 'ai_semantic_model', ['code'], unique=True)
    op.create_index(op.f('ix_ai_semantic_model_data_source_id'), 'ai_semantic_model', ['data_source_id'], unique=False)
    op.create_table('ai_question_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('question', sa.Text(), nullable=False, comment='用户问题'),
    sa.Column('semantic_model_id', sa.Integer(), nullable=True, comment='语义模型ID'),
    sa.Column('generated_sql', sa.Text(), nullable=True, comment='生成SQL'),
    sa.Column('sql_risk', sa.String(length=32), nullable=True, comment='SQL风险等级'),
    sa.Column('plan', sa.JSON(), nullable=False, comment='问数计划'),
    sa.Column('result_summary', sa.Text(), nullable=True, comment='结果摘要'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('state', sa.String(length=32), nullable=False, comment='状态'),
    sa.Column('requester', sa.String(length=64), nullable=True, comment='提问人'),
    sa.Column('requester_id', sa.BigInteger(), nullable=True, comment='提问人ID'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['ai_semantic_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_question_session_semantic_model_id'), 'ai_question_session', ['semantic_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_question_session_semantic_model_id'), table_name='ai_question_session')
    op.drop_table('ai_question_session')
    op.drop_index(op.f('ix_ai_semantic_model_data_source_id'), table_name='ai_semantic_model')
    op.drop_index(op.f('ix_ai_semantic_model_code'), table_name='ai_semantic_model')
    op.drop_table('ai_semantic_model')
    op.drop_table('aps_tasks')
    op.drop_index(op.f('ix_ai_data_source_code'), table_name='ai_data_source')
    op.drop_table('ai_data_source')
    op.drop_table('admin')
    # ### end Alembic commands ###
